name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301    
    - name: Install dependencies
      working-directory: ./TemplateProject
      run: dotnet restore
    - name: Build
      working-directory: ./TemplateProject
      run: dotnet build --configuration Release --no-restore
    - name: Build Nuget
      working-directory: ./TemplateProject
      run: dotnet pack -o ./output -c Release /p:Version=1.0.${{github.run_id}}
    - name: Push Nuget
      working-directory: ./TemplateProject
      run: dotnet nuget push /output/Superwalnut.RedisClusterTemplate.1.0.${{github.run_id}}.nupkg -k oy2ocdeouzavgv5sklxa6ccntqgmfmwuborj67o5wnj4hy -s https://api.nuget.org/v3/index.json
